# Generated by Django 4.1.7 on 2023-04-29 08:01

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="posts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "body",
                    ckeditor.fields.RichTextField(
                        blank=True, max_length=100000, null=True
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        related_name="blog_posts", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
