# Generated by Django 4.1.7 on 2023-07-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0003_alter_posts_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='slug',
            field=models.SlugField(default='unknownpost'),
            preserve_default=False,
        ),
    ]
