# Generated by Django 4.1.7 on 2023-07-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0004_posts_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_img',
            field=models.ImageField(null=True, upload_to='post_images'),
        ),
    ]
